// Generated by https://quicktype.io


export interface Directive {
  id:           string;
  // createdAt:    string;
  // apdateAt:     string;
  nombre:       string;
  descripcion:  string;
  rango_tiempo: string;
}
