// Generated by https://quicktype.io

import { Directive } from "./directives";
import { Estableishment } from "./estableishments";
import { Profile } from "./users";

export interface Ticket {
  id:            string;
  // createdAt:     string;
  // apdateAt:      string;
  descripcion:   string;
  archivo:       null;
  area:          string;
  piso:          string;
  n_sala:        string;
  n_consultorio: string;
  estado?:        string;
  user:          Profile;
  // estableishment:Estableishment;
  directive:     Directive;
  sarvey?:        null;

}
