// Generated by https://quicktype.io

import { Directive } from "./directives";
import { Estableishment } from "./estableishments";
import { Profile } from "./users";

export interface Ticket {
  id:            string;
  codigo:         number;
  createdAt:     string;
  apdateAt:      string;
  descripcion:   string;
  titulo:        string;
  files:         Files;
  area:          string;
  piso:          string;
  n_sala:        string;
  n_consultorio: string;
  estado?:        string;
  user:          Profile;
  soporteUser:   Profile;
  // estableishment:Estableishment;
  directive:     Directive;
  satisfaccion: string;
  sugerencias: string;
  ticketdetalle: TicketDetalle;
}

export interface Files {
  id:        string;
  createdAt: string;
  apdateAt:  string;
  archivo:   string;
}

export interface TicketDetalle{
  id:        string;
  createdAt: string;
  apdateAt:  string;
  detalle:   string;
}
